In [2]:
import tensorflow as tf
import numpy as np

In [19]:
five_by_five = np.reshape(np.arange(0,75), (3,5,5))
print(five_by_five)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]


In [28]:
with tf.Session() as sess:
    fbf = tf.constant(five_by_five)
    n = tf.constant(1)
    top_left = fbf[:, :n+1,:n+1]
    top_right = fbf[:, :n+1, -n:]
    bottom_left = fbf[:, -n:, :n+1]
    bottom_right = fbf[:, -n:, -n:]
    top_combined = tf.concat([top_left, top_right], axis=-1)
    bottom_combined = tf.concat([bottom_left, bottom_right], axis=-1)
    all_together = tf.concat([top_combined, bottom_combined], axis=-2)
    objs = sess.run([all_together])
    for obj in objs:
        print(obj)


[[[ 0  1  4]
  [ 5  6  9]
  [20 21 24]]

 [[25 26 29]
  [30 31 34]
  [45 46 49]]

 [[50 51 54]
  [55 56 59]
  [70 71 74]]]


In [30]:
5+2j

(5+2j)

In [41]:
tf.reset_default_graph()
real_part = tf.get_variable('real_part', initializer=5.)
imag_part = tf.get_variable('imag_part', initializer=4.)
x = tf.complex(real_part, imag_part)
y = x*tf.conj(x)
step = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(tf.real(y))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(10):
        print(sess.run([step, real_part, imag_part]))

[None, 4.9000001, 3.9200001]
[None, 4.802, 3.8416002]
[None, 4.7059603, 3.7647681]
[None, 4.6118412, 3.6894727]
[None, 4.5196042, 3.6156833]
[None, 4.4292121, 3.5433698]
[None, 4.3406277, 3.4725025]
[None, 4.2538152, 3.4030523]
[None, 4.1687388, 3.3349912]
[None, 4.0853639, 3.2682915]
