In [53]:
import numpy as np
np.set_printoptions(precision=4)
import matplotlib.pyplot as plt
import PIL

% matplotlib inline
% load_ext autoreload
% autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
print(np.__version__) # 1.13.3
print(PIL.__version__) # 4.3.0

1.13.3
4.3.0


In [17]:
from modules.create_images import open_image
from modules.create_images import downscale_image
from modules.create_images import add_to_background
from modules.create_images import make_random_size

In [4]:
dog = open_image('dog.png')
dog.show()

In [6]:
small_dog = downscale_image(dog, 100, 100)
small_dog.show()

In [16]:
added = add_to_background(dog, 32, 32, 96, 96)
added.show()

In [10]:
added.show()

In [57]:
for i in range(10):
    l, t, w, h = make_random_size()
    added = add_to_background(dog, l, t, w, h)
    added.show()


In [58]:
ls, ts, ws, hs, min_wh, max_wh = [], [], [], [], [], []
for i in range(10000):
    l, t, w, h = make_random_size()
    ls.append(l)
    ts.append(t)
    ws.append(w)
    hs.append(h)
    min_wh.append(min(w, h))
    max_wh.append(max(w, h))

all_stats = np.column_stack((ls, ts, ws, hs, min_wh, max_wh))

print(np.min(all_stats, axis=0))
print(np.max(all_stats, axis=0))
print(np.mean(all_stats, axis=0))
print(np.std(all_stats, axis=0))


[ 0  0 32 32 32 32]
[ 95  95 128 128 117 128]
[ 47.6265  47.7438  56.3496  56.1801  44.5385  67.9912]
[ 27.7897  27.6686  21.4959  21.4593  12.9799  21.8883]


In [59]:
44 + 26

70